FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt fastapi uvicorn tensorflow
COPY src/inference ./inference
COPY models ./models
CMD ["uvicorn", "inference/predict:app", "--host", "0.0.0.0", "--port", "8000"]
